"""
VeriSight Report Generator
"""

from datetime import datetime


def generate_report(
    claim,
    verdict,
    confidence,
    reasoning,
    evidence
):
    report = []

    report.append("=" * 60)
    report.append("VERISIGHT VERIFICATION REPORT")
    report.append("=" * 60)
    report.append("")
    report.append(f"Generated: {datetime.now()}")
    report.append("")
    report.append("CLAIM")
    report.append("-" * 60)
    report.append(claim)
    report.append("")
    report.append("VERDICT")
    report.append("-" * 60)
    report.append(verdict)
    report.append("")
    report.append(f"Confidence: {confidence}%")
    report.append("")
    report.append("REASONING")
    report.append("-" * 60)
    report.append(reasoning)
    report.append("")
    report.append("TOP EVIDENCE")
    report.append("-" * 60)

    if evidence:

        for i, article in enumerate(evidence, 1):

            report.append(f"{i}. {article['title']}")
            report.append(f"Source : {article['source']}")
            report.append(f"Similarity : {article['similarity']:.2f}")

            if article.get("link"):
                report.append(article["link"])

            report.append("")

    else:

        report.append("No supporting evidence found.")

    report.append("=" * 60)
    report.append("Generated by VeriSight Neural Intelligence")
    report.append("=" * 60)

    return "\n".join(report)